services:
  db1:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: Comandas
    ports:
    - "5433:5432"
    volumes:
    - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5050:80"
    depends_on:
    - db1
volumes:
 pgdata:
